version: '3.8'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: aStrong(!)Password 
      MSSQL_PID: Developer
    ports:
      - 1433:1433

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
